config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings
      resources :diaries, only: [:index]
      resources :sessions, only: [:create]
      resources :patients, only: [:index]
      resources :debtors, only: [:index]
    end
  end

  resources :diaries, only: [:index]
  resources :bookings do
    get 'search', on: :collection
  end
  resources :entities, only: [:index] do
    resources :diaries, only: [:index]
  end

  root "entities#index"
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_many :diaries

  validates :username, uniqueness: true
  validates :username, :password, presence: true
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @entities = Entity.all
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<td><%= entity.uid %></td>
<td><%= entity.title %></td>
<td><%= entity.description.truncate(20) %></td>
<td data-controller="entity-ui">
  <a href="<%= diaries_path(entity_id: entity.id) %>" name="session-button" id="js-auth-btn"
          class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          data-entity-ui-credentials-value="<%= entity&.token || "#{entity.username}:#{entity.password}" %>"
          data-action="click->entity-ui#authenticate">
    <b>DIARY</b>
  </a>
</td>

app/views/entities/index.html.erb
<div class="container border-b border-gray-900/10 mt-6 pb-12" data-controller="entity-ui">
  <h2 class="text-blue-500 text-4xl font-semibold mt-10">Entities</h2>

  <table class="table flex-table table-striped tftable" border="1">
    <thead>
      <tr>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">ID</th>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">Title</th>
        <th class="p-3 text-sm font-semibold text-left text-gray-700 bg-gray-200">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @entities.each do |entity| %>
        <tr>
          <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
            <%= entity.id %>
          </td>
          <td class="px-3 py-4 text-sm font-normal text-left text-gray-600 bg-gray-50">
            <%= entity.title %>
          </td>
          <td class="px-3 py-4 text-sm font-normal text-left text-red-600 underline break-words bg-light">
            <%= link_to "Login", entity_diaries_path(entity),
                                 data: {
                                  username: entity.username,
                                  password: entity.password,
                                  action: "click->entity-ui#login"
                                 },
                                 class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>