config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings
      resources :diaries, only: [:index]
      resources :sessions, only: [:create]
      resources :patients, only: [:index]
      resources :debtors, only: [:index]
    end
  end

  resources :diaries, only: [:index]
  resources :bookings do
    get 'search', on: :collection
  end
  resources :entities, only: [:index] do
    resources :diaries, only: [:index]
  end

  root "entities#index"
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :entity
  has_many :bookings
end

app/controllers/api/v1/diaries_controller.rb
class Api::V1::DiariesController < ApplicationController
  # GET /api/v1/diaries
  def index
    render json: GxWeb::Client.new.list_diaries || Diary.all
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :load_entity

  def index
    @diaries = Diary.all

    respond_to do |format|
      format.html
      format.json {
        render json: @diaries
      }
    end
  end

  private

  def load_entity
    @entity = Entity.find(params[:entity_id])
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_booking.html.erb
<ul data-diary-ui-start-at-value="<%= booking.start_at %>"
    data-diary-ui-duration-value="<%= booking.duration %>">
   <li>DATE: <b><%= booking.start_at %></b> (<%= booking.duration %>s)</li>
   <li>STATE: <b><%= booking.status %></b> (<%= booking.booking_type %>)</li>
</ul>

app/views/diaries/_diary.html.erb
<tr>
  <td><%= diary.id %></td>
  <td><%= diary.name %></td>
  <td colspan="3" class="actions text-center">
    <%= link_to "View", bookings_path(diary_id: diary.id), class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
  </td>
</tr>

app/views/diaries/index.html.erb
<div class="container border-b border-gray-900/10 mt-6 pb-12" data-controller="diary-ui">
  <h2 class="font-semibold text-4xl text-blue-500">Diaries</h2>

  <div id="diaries">
    <table class="tftable mt-10">
      <thead>
        <tr>
          <th class="text-left">UID</th>
          <th class="text-left">NAME</th>
          <th colspan="3" class="text-center">BOOKINGS</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "diary", collection: @diaries %>
      </tbody>
    </table>
  </div>
</div>