config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bookings
      resources :diaries, only: [:index]
      resources :sessions, only: [:create]
      resources :patients, only: [:index]
      resources :debtors, only: [:index]
    end
  end

  resources :diaries, only: [:index]
  resources :bookings do
    get 'search', on: :collection
  end
  resources :entities, only: [:index] do
    resources :diaries, only: [:index]
  end

  root "entities#index"
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :diary
  has_one :debtor
  has_one :patient

  AVAILABLE_STATES = [
    'Booked',
    'Arrived',
    'Ready',
    'Treated',
    'Billed',
    'Done'
  ].freeze

  AVAILABLE_TYPES = [
    'Meeting',
    'Follow up',
    'Consultation',
    'Out of office'
  ].freeze

  validates :diary, :reason, :start_time, presence: true

  scope :earliest, -> { reorder(start_time: :asc) }
  scope :latest, -> { reorder(start_time: :desc) }
  scope :daily, -> {
    where(start_time: (Time.now.midnight - 1.day)..Time.now.midnight)
  }
  scope :weekly, -> {
    where(start_time: (7.days.ago)..Time.now.midnight)
  }
  scope :monthly, -> {
    beginning_of_month = Date.today.beginning_of_month
    end_of_month = beginning_of_month.end_of_month
    where(start_time: beginning_of_month..end_of_month)
  }

  def scheduled_at
    self.start_time.to_date
  end

  def daily_appointment
    where(start_time: Date.today.all_day)
  end

  def timestamp
    scheduled_at || daily_appointment
  end
end

app/models/booking_type.rb
# frozen_string_literal: true

class BookingType < ApplicationRecord
  belongs_to :bookable, polymorphic: true
  belongs_to :booking, foreign_key: "booking_uid", optional: true
  has_and_belongs_to_many :diaries, foreign_key: "diary_uid", optional: true

  TYPES_OF_BOOKINGS = [ 'Meeting', 'Follow up', 'Consultation', 'Out of office' ].freeze
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show update destroy ]

  # GET /bookings
  def index
    @bookings = Booking.all

    render json: @bookings
  end

  # GET /bookings/1
  def show
    render json: @booking
  end

  # GET /bookings/search/2023-12-01
  def search
    @bookings = Booking.find_by(start_at: params[:date])

    render json: @bookings
  end

  # POST /bookings
  def create
    @booking = Booking.new(permitted_params)

    if @booking.save
      render json: @booking, status: :created, location: @booking
    else
      render json: @booking.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if @booking.update(permitted_params)
      render json: @booking
    else
      render json: @booking.errors, status: :unprocessable_entity
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
  end

  private

    def set_booking
      @booking = Booking.find(params[:id])
    end

    def permitted_params
      params.require(:bookings).permit(
        :entity_uid,
        :diary_uid,
        :booking_type_uid,
        :booking_status_uid,
        :patient_uid,
        :start_time,
        :duration,
        :reason,
        :cancelled
      )
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :load_booking_data, only: [:new, :edit]

  def index
    @bookings = Booking.all.order(created_at: :desc)
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(permitted_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to bookings_path }
        format.turbo_stream
      else
        format.html {
          puts @booking.errors.full_message
          @patients = Patient.all
          @debtors = Debtor.all

          render :new
        }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @booking.update(permitted_params)
        format.html { redirect_to bookings_path }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("booking_#{@booking.id}", partial: 'booking', locals: { booking: @booking })
        end
      else
        format.html { redirect_to edit_booking_path }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @booking.destroy
        format.html {
          redirect_to bookings_path
        }
        format.turbo_stream
      else
        format.html { redirect_to bookings_path, notice: @booking.errors.full_message }
      end
    end
  end

  def search
    @bookings = Booking.where(start_time: params[:date].to_date.all_day)

    respond_to do |format|
      format.json {
        render json: render_to_string(partial: 'bookings/booking', collection: @bookings, formats: [:html])
      }
    end
  end

  private

  def set_booking
    @booking = Booking.joins(:diary).find(params[:id])
  end

  def permitted_params
    params
      .require(:booking)
      .permit(
        :reason,
        :end_at,
        :duration,
        :start_time,
        :diary_id,
        :debtor_id,
        :patient_id,
        :booking_type_uid,
        :booking_status_uid,
      )
  end

  def load_booking_data
    @patients = Patient.all
    @debtors = Debtor.all
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def empty_options
    options_for_select([])
  end

  def patients_for_select(selected: nil, records: [])
    return empty_options unless records.present?

    patients = records.collect { |patient| [ patient.name, patient.id ] }
                      .sort_by { |patient| patient[1].to_i }

    selected ? options_for_select(patients, selected:) : options_for_select(patients)
  end

  def debtors_for_select(selected: nil, records: [])
    return empty_options unless records.present?

    debtors = records.collect { |debtor| [ debtor.name, debtor.id ] }
                     .sort_by { |debtor| debtor[1].to_i }

    selected ? options_for_select(debtors, selected:) : options_for_select(debtors)
  end

  def booking_types_for_select(selected: nil)
    BookingType.all.collect do |booking_type|
      [booking_type.name, booking_type.bookable_id]
    end.uniq
  end

end

app/views/bookings/_booking.html.erb
<%= turbo_frame_tag "booking_#{booking.id}" do %>
  <table class='booking-table'>
    <tbody>
      <tr>
        <td class="text-sm font-normal text-left text-gray-600 bg-gray-50">
          <%= booking.reason %>
        </td>
        <td class="text-sm font-normal text-left text-gray-600 bg-gray-50">
          <%= booking.start_time %>
        </td>
        <td class="table-links text-blue-500">
          <%= link_to booking_path(booking), data: {turbo: false}, title: "Show Calendar" do %>
            <i id="calendar" class="icon fa fa-calendar calendar cursor-pointer"></i>
          <% end %>
        </td>
        <td class="table-links text-gray-600">
          <%= link_to edit_booking_path(booking), data: { action: "click->booking-ui#showForm" } do %>
            <i id="edit" class="icon fa fa-edit edit cursor-pointer"></i>
          <% end %>
        </td>
        <td class="table-links text-red-600">
          <%= link_to booking_path(booking), style: 'margin-left: 5px', data: {confirm: "Are you sure?", "turbo-method": :delete} do %>
            <i id="trash" class="icon fa fa-trash trash cursor-pointer"></i>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/bookings/_debtor.html.erb
<style type="text/css">
    .tftable {font-size:14px;color:#333333;width:100%;border-width: 1px;border-color: #87ceeb;border-collapse: collapse;}
    .tftable th {font-size:18px;background-color:#87ceeb;border-width: 1px;padding: 8px;border-style: solid;border-color: #87ceeb;text-align:left;}
    .tftable tr {background-color:#ffffff;}
    .tftable td {font-size:14px;border-width: 1px;padding: 8px;border-style: solid;border-color: #87ceeb;}
    .tftable tr:hover {background-color:#e0ffff;}
</style>

<table class="tftable" border="1">
    <tr>
        <th>UID</th>
        <th>Entity UID</th>
        <th>Name</th>
        <th>Surname</th>
    </tr>
    
    {{#each response.data}}
        <tr>
            <td>{{uid}}</td>
            <td>{{entity_uid}}</td>
            <td>{{name}}</td>
            <td>{{surname}}</td>
        </tr>
    {{/each}}
</table>

app/views/bookings/_form.html.erb
<%= form_with(model: @booking, local: true, class: "my-10") do |f| %>
  <div class="form form-inline">
    <%= f.hidden_field :diary_id, value: @booking&.diary&.id || Diary.last.id %>

    <% if @booking.errors.any? %>
      <div class="alert alert-danger mt-2" role="alert">
        <ul>
          <% @booking.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="space-y-12">
      <div class="border-b border-gray-900 pb-12">
        <h2 class="font-bold text-7xl text-slate-600">Booking</h2>

        <div class="mt-10 grid grid-cols-3 gap-x-4 gap-y-8 sm:grid-cols-6">
          <div class="sm:col-span-3 mt-4">
            <label for="booking_start_at" class="block text-sm font-medium leading-6 text-gray-900">When is your appointment?</label>
            <div class="mt-2">
              <input type="datetime-local" name="booking[start_time]" id="booking_start_time" value="<%= @booking&.start_time || Date.today %>" autocomplete="start-time" class="form-input date block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>

          <div class="sm:col-span-3 mt-4">
            <label for="booking_duration" class="block text-sm font-medium leading-6 text-gray-900">How long is your appointment?</label>
            <div class="mt-2">
              <input type="number" name="booking[duration]" id="booking_duration" value="<%= @booking&.duration || 1 %>" class="form-input date block w-full rounded border-gray-200 sm:text-sm" />
            </div>
          </div>

          <div class="sm:col-span-3 mt-4">
            <%= f.label :debtor_id, "Debtor", class: 'label block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <%= f.select :debtor_id, debtors_for_select(records: @debtors, selected: @booking&.debtor_id),
                                      { include_blank: true },
                                      { class: 'select block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50' } %>
            </div>
          </div>

          <div class="sm:col-span-3 mt-4">
            <%= f.label :patient_id, "Patient", class: 'label block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <%= f.select :patient_id, patients_for_select(records: @patients, selected: @booking&.patient_id),
                                        { include_blank: true },
                                        { class: 'select block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50' } %>
            </div>
          </div>

          <div class="sm:col-span-3 mt-4">
            <%= f.label :booking_type_uid, "Booking type", class: 'label block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <%= f.select :booking_type_uid, booking_types_for_select(selected: @booking&.booking_type_uid),
                                          { include_blank: true },
                                          { required: true, class: 'select block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50' } %>
            </div>
          </div>

        <div class="sm:col-span-3 mt-4">
            <%= f.label :booking_status_uid, "Booking status", class: 'label block text-sm font-medium leading-6 text-gray-900' %>
            <div class="mt-2">
              <%= f.select :booking_status_uid, Booking::AVAILABLE_STATES, { include_blank: true }, { required: true, class: 'select block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50' } %>
            </div>
          </div>

          <div class="sm:col-span-3 mt-10">
            <%= link_to "Cancel", bookings_path(diary_id: @booking.diary_id),
                                  class: 'bg-gray-800 px-3 py-2 hover:bg-gray-700 text-white text-sm font-semibold px-4 py-1 border border-gray-700 rounded-lg shadow-sm',
                                  data: { action: "click->booking-ui#hideForm" } %>
            <%= f.submit "Save", class: 'rounded-md bg-indigo-600 px-6 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600', data: { action: "click->booking-ui#hideForm" } %>
          </div>

          <div class="sm:col-span-3 mt-4">
            <label for="booking_reason" class="block text-sm font-medium leading-6 text-gray-900">What is the reason for your appointment?</label>
            <div class="mt-2">
              <input type="text" name="booking[reason]" id="booking_reason" value="<%= @booking&.reason %>" autocomplete="reason" class="form-input block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/create.turbo_stream.erb
<%= turbo_stream.append "bookings" do %>
    <%= turbo_frame_tag dom_id(@booking) do %>
        <%= render "bookings/booking", booking: @booking %>
    <% end %>
<% end %>
<%= turbo_stream_from 'bookings' %>

app/views/bookings/destroy.turbo_stream.erb
<%= turbo_stream.remove "booking_#{@booking.id}" %>

app/views/bookings/edit.html.erb
<div class="flex justify-center border-b border-gray-900/10 pb-12">
  <h1 class="text-base font-semibold text-blue-500">Edit Booking</h1>

  <div class="flex flex-col">
    <%= turbo_frame_tag "booking_#{@booking.id}" do %>
      <%= render partial: 'form', object: @booking %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container border-b border-gray-900/10 py-8" data-controller="booking-ui">
  <h1 class="text-blue-500 text-4xl font-semibold mt-10">Bookings</h1>

  <div class="mt-10" data-controller='search'>
    <%= date_field_tag :date,'', placeholder: 'Search by date', data: {
            :action => 'change->search#search',
            :search_url => search_bookings_path,
            :'search-target' => 'params' } %>

      <div class="flex mt-6 break-before-all">
        <%= turbo_frame_tag "create_booking_form" do %>
          <%= link_to 'New Appointment', new_booking_path,
                class: 'rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600',
                data: { action: "click->booking-ui#showForm" } %>
        <% end %>
      </div>
  </div>

  <div class="w-full bg-light" id="diary-bookings">
    <div id="bookings" class='flex flex-col mt-10 w-1/2'>
      <%= turbo_stream_from 'bookings' %>

      <table class="booking-table <%= 'hidden' if @bookings.empty? %>">
        <thead>
          <tr>
            <th class="text-sm font-semibold text-left text-gray-700 bg-gray-200">
              REASON
            </th>
            <th class="text-sm font-semibold text-left text-gray-700 bg-gray-200">
              DATE
            </th>
            <th colspan="3" class="table-links text-sm font-semibold text-left text-gray-700 bg-gray-200"></th>
          </tr>
        </thead>
      </table>
      <%= turbo_frame_tag "bookings" do %>
        <% if @bookings.any? %>
          <%= render @bookings %>
        <% else %>
          <p>No bookings available</p>
        <% end %>
      <% end %>
    </div>
    <br />
    <div class="flex flex-col">
      <div id="patients" class="flex w-1/2"></div>
      <div id="debtors" class="flex w-1/2"></div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="flex justify-center border-b border-gray-900/10 pb-12">
  <h1 class="text-base font-semibold text-blue-500">New Booking</h1>

  <div class="flex flex-col">
    <%= turbo_frame_tag "create_booking_form" do %>
      <%= render partial: 'form', object: @booking %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="w-full h-screen bg-slate-800 overflow-x-hidden">
  <div class="container min-h-[650px] relative w-[] mx-auto p-5px flex rounded-[10px]">
      <!-- left -->
      <div class="left w-1/2 p-5">
          <div id="calender" class="calender relative w-full h-full flex flex-col flex-wrap justify-between  text-rounded-[5px] bg-white">
              <div id='month' class="month flex text- justify-between items-center w-full h-24 px-14 text-lg font-semibold capitalize">
                <i id="prev" class="icon fa fa-angle-left prev cursor-pointer"></i>
                <span id="date" class="date text-center">

                </span>
                <i id="next" class="icon fa fa-angle-right next cursor-pointer"></i>
              </div>
              <div id='weekdays' class="weekdays flex space-x-2 w-full px-7 text-base font-semibold capitalize justify-between  items-center">
                <span class="h-full flex justify-center items-center">Sun</span>
                <span class="h-full flex justify-center items-center">Mon</span>
                <span class="h-full flex justify-center items-center">Tue</span>
                <span class="h-full flex justify-center items-center">Wed</span>
                <span class="h-full flex justify-center items-center">Thur</span>
                <span class="h-full flex justify-center items-center">Fri</span>
                <span class="h-full flex justify-center items-center">Sat</span>
              </div>
              <div id='days' class="days flex flex-wrap w-full justify-between px-6 text-base mb-6 font-semibold">
                <div class="day next-date h-[50px] flex justify-center items-center cursor-pointer   w-[13%]"></div>
              </div>
              <div id="goto-today" class="goto-today w-full h-[50px] items-center flex justify-between space-x-1 px-5 mb-5">
                  <div id="goto" class="goto flex items-center rounded-[5px] overflow-hidden border-[1px] border-gray-300">
                      <input type="text" placeholder="dd/mm/yyyy" id="date-input" class="date-input text-green-800 outline-none rounded-base py-2 px-5 w-full h-6 rounded-md">
                      <button id="goto-btn" class="goto-btn py-2 px-3 rounded-md bg-transparent border-[1px] text-green-800 hover:text-white hover:bg-orange-600">Go</button>
                  </div>
                  <button id="today-btn" class='today-btn  py-2 px-3 rounded-md bg-transparent border-[1px] text-green-800 hover:text-white hover:bg-green-600'>today</button>
              </div>
          </div>
      </div>
      <!-- right -->
      <div class="right relative w-[40%] text-white min-h-[100%] px-0 py-8">
          <div class="today-date flex w-full h-16 flex-wrap space-x-8 justify-between items-center capitalize mt-12 mb-6 px-10 py-0 pl-[70px]">
              <div class="event-day text-2xl font-semibold">Mon</div>
              <div class="event-date text-base text-gray-50 font-normal">4, September 2023</div>
          </div>
          <div id="events" class="events w-full h-full max-w-[] overflow-y-auto overflow-x-hidden flex flex-col p-1 relative">
              <div class="event relative w-[95%] h-[70px] flex justify-center flex-col space-x-[5px] color-white px-[20px] pl-[50px] cursor-pointer bg-gradient-to-r from-yellow-400 to-transparent">
                  <div class="title flex items-center pointer-events-none">
                      <i class="fas fa-circle"></i>
                      <h3 class=" event-title text-base ml-[20px]">Event 1</h3>
                  </div>
                  <div class="event-time text-sm font-normal pointer-events-none ml-[5px]">
                      7:00AM - 4:00PM
                  </div>
              </div>
          </div>
          <div class="add-event-wrapper">
              <div class="add-event-header">
                  <div class="title">Add Event</div>
                  <i class="fas fa-times close"></i>
              </div>
              <div class="add-event-body w-full h-full flex flex-col space-y-[5px] p-[20px]">
                  <div class="add-event-input">
                      <input type="text" placeholder="Event Name" class="event-name" />
                  </div>
                  <div class="add-event-input">
                      <input
                          type="text"
                          placeholder="Event Time From"
                          class="event-time-from"
                          value="<%= @booking&.start_time %>"
                      />
                  </div>
                  <div class="add-event-input">
                      <input
                          type="text"
                          placeholder="Event Time To"
                          class="event-time-to"
                          value="<%= @booking&.end_at %>"
                      />
                  </div>
              </div>
              <div class="add-event-footer">
                  <button class="add-event-btn">Add Event</button>
              </div>
          </div>
          <button class="add-event z-index absolute right-0 bottom-[150px] w-[40px] h-[40px] items-center justify-center text-base border-[2px] border-white rounded-[50%] cursor-pointer bg-transparent opacity-50 hover:opacity-100">
              <i class="fas fa-plus pointer-events-none"></i>
          </button>
      </div>
   </div>
 </div>

app/views/bookings/update.turbo_stream.erb
<%= turbo_stream_from 'bookings' %>